### ISSUE TITLE
没太明白这个插件的作用

### ISSUE THREAD

**Issue by guotao** [whistle-plugins/whistle.proxyauth#1]
`if (!AUTH_RE.test(req.headers.authorization) ||
          (decodeBase64(RegExp.$1) !== ruleValue)) {
        return res.end(ERR_RULES);
      }`

意思是设置代理的时候需要勾选“认证”，并填写设置的密码么。可是为什么又可以针对某个域名设置不同密码呢。

**Comment by avwo** [comment]
用户名和密码是配置里面设置的，`ruleValue` 就是

**Comment by guotao** [comment]
![image](https://user-images.githubusercontent.com/46209/57513405-b8f9f180-7340-11e9-8902-6521ae84e130.png)
多谢回复，请问这里的用户名和密码，是在底部勾选“鉴定”后填写的吗？

**Comment by avwo** [comment]
试试看就知道了
