### ISSUE TITLE
请问如何搭配pm2使用

### ISSUE THREAD

**Issue by guotao** [whistle-plugins/whistle.proxyauth#2]
插件安装到全局了，配置页里找不到，pm2的全局模块里也装了，也找不到，不知道有么有解决过类似问题的，求指教。

**Comment by avwo** [comment]
不需要pm2，这个要安装whistle，安装后用  `w2 start` 启动whistle即可，whistle会自动全局搜索插件

**Comment by guotao** [comment]
抱歉，忘记交代上下文了，我是部署在内网服务器，为了做服务监控用了pm2和koa－whistle的。

**Comment by avwo** [comment]
把插件放到项目的依赖里面试试
